import { useEffect, useState } from "react";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { Activity, BarChart3, Check, FileText, Globe2, KeyRound, LayoutGrid, LockKeyhole, Megaphone, MoreHorizontal, Save, Search, Settings2, ShieldCheck, SlidersHorizontal, Users, Wrench } from "lucide-react";

type ToolRow = { key: string; bn: string; en: string; enabled: boolean; status: string };
const defaultTools: ToolRow[] = [
  { key: "image-pdf", bn: "ছবি থেকে PDF", en: "JPG to PDF", enabled: true, status: "ready" },
  { key: "pdf-image", bn: "PDF থেকে ছবি", en: "PDF to Image", enabled: true, status: "ready" },
  { key: "merge", bn: "PDF জোড়া লাগান", en: "Merge PDF", enabled: true, status: "ready" },
  { key: "split", bn: "PDF ভাগ করুন", en: "Split PDF", enabled: true, status: "ready" },
  { key: "compress", bn: "PDF ছোট করুন", en: "Compress PDF", enabled: true, status: "ready" },
  { key: "editor", bn: "PDF এডিট করুন", en: "PDF Editor", enabled: true, status: "basic" },
  { key: "pdf-word", bn: "PDF থেকে Word", en: "PDF to Word", enabled: false, status: "coming-soon" },
  { key: "ocr", bn: "বাংলা OCR", en: "Bangla OCR", enabled: false, status: "limited" },
];
const nav = ["Overview", "Tools", "Content & SEO", "Ads", "Settings", "Access"];

function Gate({ denied = false }: { denied?: boolean }) { return <div className="admin-gate"><div className="admin-gate-card"><span className="admin-gate-mark">{denied ? <ShieldCheck size={25} /> : <LockKeyhole size={25} />}</span><p className="admin-kicker">{denied ? "ACCESS DENIED / অনুমতি নেই" : "PRIVATE AREA / ADMIN ONLY"}</p><h1>{denied ? "এই panel আপনার জন্য নয়" : "Admin panel-এ ঢুকুন"}</h1><p>{denied ? "Admin role না থাকায় এই area দেখা যাচ্ছে না। Owner account দিয়ে আবার login করুন।" : "এই page শুধু website owner-এর জন্য। Secure login করে panel access করুন।"}</p>{!denied && <button type="button" className="admin-primary" onClick={() => startLogin()}>Secure login <KeyRound size={16} /></button>}<a href="/">← Public website-এ ফিরুন</a></div></div>; }

export default function Admin() {
  const { user } = useAuth();
  return <DashboardLayout>{!user ? <Gate /> : user.role !== "admin" ? <Gate denied /> : <AdminContent userName={user.name ?? "Owner"} />}</DashboardLayout>;
}

function AdminContent({ userName }: { userName: string }) {
  const [tab, setTab] = useState("Overview");
  const [tools, setTools] = useState<ToolRow[]>(defaultTools);
  const [siteName, setSiteName] = useState("Paperly");
  const [meta, setMeta] = useState("Free online PDF tools for everyone — JPG to PDF, merge, split and compress in your browser.");
  const [adsEnabled, setAdsEnabled] = useState(false);
  const [saved, setSaved] = useState(false);
  const toolQuery = trpc.admin.toolSettings.useQuery(undefined, { enabled: true });
  const toggleMutation = trpc.admin.toggleTool.useMutation({ onSuccess: () => void toolQuery.refetch(), onError: () => toast.error("Save হয়নি / Could not save") });
  const settingMutation = trpc.admin.saveSetting.useMutation({ onSuccess: () => { setSaved(true); toast.success("Saved / Save হয়েছে"); setTimeout(() => setSaved(false), 1600); }, onError: () => toast.error("Save হয়নি / Could not save") });
  useEffect(() => { if (toolQuery.data?.length) setTools(toolQuery.data.map((tool) => ({ key: tool.toolKey, bn: tool.nameBn, en: tool.nameEn, enabled: Boolean(tool.enabled), status: tool.status }))); }, [toolQuery.data]);
  const active = tools.filter((tool) => tool.enabled).length;
  const save = (key: string, value: string) => settingMutation.mutate({ settingKey: key, value });
  const toggle = (tool: ToolRow) => { const enabled = !tool.enabled; setTools((items) => items.map((item) => item.key === tool.key ? { ...item, enabled } : item)); toggleMutation.mutate({ toolKey: tool.key, enabled }); };
  return <div className="admin-page"><div className="admin-page-head"><div><p className="admin-kicker">PAPERLY CONTROL ROOM</p><h1>{tab === "Overview" ? "Overview / সারাংশ" : tab}</h1><p>Welcome back, {userName}. Website-এর সব গুরুত্বপূর্ণ control এক জায়গায়।</p></div><div className="admin-head-actions"><span><span className="admin-live-dot" /> Live</span><button type="button" className="admin-save" onClick={() => save("last_saved", new Date().toISOString())}>{saved ? <Check size={15} /> : <Save size={15} />} {saved ? "Saved" : "Save changes"}</button></div></div><div className="admin-tabbar">{nav.map((item) => <button type="button" key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>{tab === "Overview" && <Overview active={active} total={tools.length} setTab={setTab} />}{tab === "Tools" && <ToolManager tools={tools} toggle={toggle} />}{tab === "Content & SEO" && <ContentManager siteName={siteName} setSiteName={setSiteName} meta={meta} setMeta={setMeta} save={save} />}{tab === "Ads" && <AdsManager enabled={adsEnabled} setEnabled={setAdsEnabled} save={save} />}{tab === "Settings" && <SettingsManager siteName={siteName} setSiteName={setSiteName} save={save} />}{tab === "Access" && <AccessManager />}</div>;
}

function Overview({ active, total, setTab }: { active: number; total: number; setTab: (tab: string) => void }) { return <><div className="admin-stat-grid"><div><span><Activity size={16} /> Tool runs · এই মাস</span><strong>—</strong><small>Anonymous events not connected</small></div><div><span><Check size={16} /> Successful</span><strong>—</strong><small>Connect analytics to measure</small></div><div><span><LayoutGrid size={16} /> Active tools</span><strong>{active}<small> / {total}</small></strong><small>Core tools online</small></div><div><span><Globe2 size={16} /> Indexed pages</span><strong>—</strong><small>Verify in Search Console after deploy</small></div></div><div className="admin-panel-grid"><section className="admin-panel"><div className="panel-heading"><span><BarChart3 size={17} /> Usage overview / ব্যবহারের সারাংশ</span><button type="button" className="panel-filter">Last 30 days <MoreHorizontal size={15} /></button></div><div className="fake-chart"><div className="chart-y"><span>400</span><span>300</span><span>200</span><span>100</span><span>0</span></div><div className="chart-lines"><span /><span /><span /><span /><div className="chart-empty">Analytics off · no events stored</div><div className="chart-x"><span>01</span><span>07</span><span>14</span><span>21</span><span>30</span></div></div></div></section><section className="admin-panel"><div className="panel-heading"><span><Wrench size={17} /> Quick controls / দ্রুত নিয়ন্ত্রণ</span></div><div className="quick-list"><button type="button" onClick={() => setTab("Tools")}><span><SlidersHorizontal size={16} /><strong>Tool availability</strong><small>{active} active tools</small></span><span className="quick-arrow">→</span></button><button type="button" onClick={() => setTab("Content & SEO")}><span><Search size={16} /><strong>SEO health</strong><small>Metadata editor ready</small></span><span className="quick-status">Good</span></button><button type="button" onClick={() => setTab("Ads")}><span><Megaphone size={16} /><strong>AdSense slots</strong><small>Control before approval</small></span><span className="quick-status muted">Off</span></button></div></section></div></>; }

function ToolManager({ tools, toggle }: { tools: ToolRow[]; toggle: (tool: ToolRow) => void }) { return <section className="admin-panel tool-manager"><div className="panel-heading"><span><Wrench size={17} /> Tool manager / টুল নিয়ন্ত্রণ</span><button type="button" className="admin-outline">+ Add tool</button></div><p className="panel-intro">Public website-এ কোন tool দেখা যাবে, কোনটি Coming Soon থাকবে—এখান থেকে ঠিক করুন।</p>{tools.map((tool) => <div className="managed-tool" key={tool.key}><span className={`managed-icon ${tool.enabled ? "on" : "off"}`}><FileText size={17} /></span><span><strong>{tool.bn}</strong><small>{tool.en} · {tool.status}</small></span><span className={`tool-state ${tool.enabled ? "on" : ""}`}>{tool.enabled ? "Active" : tool.status}</span><button type="button" className={`admin-toggle ${tool.enabled ? "on" : ""}`} onClick={() => toggle(tool)} aria-label={`Toggle ${tool.en}`}><span /></button><button type="button" className="row-more"><MoreHorizontal size={16} /></button></div>)}</section>; }

function FormPanel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="admin-panel form-panel"><div className="panel-heading"><span>{icon} {title}</span></div>{children}</section>; }
function ContentManager({ siteName, setSiteName, meta, setMeta, save }: { siteName: string; setSiteName: (value: string) => void; meta: string; setMeta: (value: string) => void; save: (key: string, value: string) => void }) { return <FormPanel title="Content & SEO / কনটেন্ট এবং SEO" icon={<Search size={17} />}><label>Brand name / নাম<input value={siteName} onChange={(event) => setSiteName(event.target.value)} /></label><label>Meta description / Google description<textarea value={meta} onChange={(event) => setMeta(event.target.value)} rows={4} /></label><p className="field-help">বাংলা ও English keyword naturally রাখুন। Current page: `/` · `/tools` pages are ready for future landing content.</p><button type="button" className="admin-primary form-save" onClick={() => { save("site_name", siteName); save("meta_description", meta); }}>Save SEO content <Save size={15} /></button></FormPanel>; }
function AdsManager({ enabled, setEnabled, save }: { enabled: boolean; setEnabled: (value: boolean) => void; save: (key: string, value: string) => void }) { return <FormPanel title="Ad slot manager / বিজ্ঞাপন" icon={<Megaphone size={17} />}><p className="panel-intro">AdSense approve হওয়ার আগে ads off রাখুন। Approve হলে slot on করে code যোগ করা যাবে।</p><div className="ad-slot"><span><strong>Result below / result-এর পরে</strong><small>Responsive display ad</small></span><button type="button" className={`admin-toggle ${enabled ? "on" : ""}`} onClick={() => setEnabled(!enabled)}><span /></button></div><div className="ad-slot"><span><strong>Tool page top / tool-এর উপরে</strong><small>Mobile-friendly banner</small></span><button type="button" className="admin-toggle"><span /></button></div><button type="button" className="admin-primary form-save" onClick={() => save("ads_enabled", String(enabled))}>Save ad settings <Save size={15} /></button></FormPanel>; }
function SettingsManager({ siteName, setSiteName, save }: { siteName: string; setSiteName: (value: string) => void; save: (key: string, value: string) => void }) { return <FormPanel title="Site settings / সেটিংস" icon={<Settings2 size={17} />}><label>Website name<input value={siteName} onChange={(event) => setSiteName(event.target.value)} /></label><label>Canonical URL<input placeholder="https://your-domain.com" /></label><label>Default language<select defaultValue="bn"><option value="bn">বাংলা + English</option><option value="en">English + বাংলা</option></select></label><p className="field-help">File processing remains browser-based. এই settings শুধু website identity এবং metadata control করে।</p><button type="button" className="admin-primary form-save" onClick={() => save("site_name", siteName)}>Save site settings <Save size={15} /></button></FormPanel>; }
function AccessManager() { return <FormPanel title="Admin access / অনুমতি" icon={<Users size={17} />}><div className="access-card"><span className="admin-gate-mark"><ShieldCheck size={19} /></span><span><strong>Owner access</strong><small>Protected by Manus OAuth and admin role</small></span><span className="quick-status">Active</span></div><div className="access-card"><span className="admin-gate-mark"><LockKeyhole size={19} /></span><span><strong>Admin link</strong><small>`/admin` — public navigation থেকে আলাদা রাখা যাবে</small></span><span className="quick-status">Protected</span></div><p className="field-help">নতুন admin যোগ বা role change database-এর user role থেকে করতে হবে। Public user-কে কখনো admin link বা permission দেবেন না।</p></FormPanel>; }
